# Generated by Django 4.2.9 on 2024-02-06 13:21

from django.db import migrations, models
import django_jupyter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notebook",
                    django_jupyter.models.JupyterNotebookField(
                        upload_to=django_jupyter.models.JupyterNotebookField.upload_path
                    ),
                ),
            ],
        ),
    ]
